Homework 4
polisgo2020/search-K1ta pull request #4
Opened 2020-04-06 21:32 UTC by K1ta

2020-04-07 20:07 UTC, tariel-x requested changes
По заданию необходимо:
```
Параллельно должны происходить:
    чтение файлов;
    обработка токенов.
```

2020-04-07 20:07 UTC, tariel-x commented on main.go
> +	case "start":
Может стоит использовать что-нибудь вроде https://github.com/urfave/cli ?

2020-04-11 18:20 UTC, tariel-x commented
> По заданию необходимо:
> 
> ```
> Параллельно должны происходить:
>     чтение файлов;
>     обработка токенов.
> ```

Прошу прощения, забыл, какую договорённость достигли в прошлом mr.

2020-04-11 18:34 UTC, tariel-x requested changes
Сломано чтение индекса:
```
$ ./search-K1ta start index.txt 8080
Cannot read index from file 'index.txt': invalid format of words map in index
```

2020-04-11 18:34 UTC, tariel-x commented on main.go
> +	exitIfNotEnoughArgs := func(length int) {
Несмотря на эту функцию, получается не очень хорошо:
```
$ ./search-K1ta 
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.main()
        /home/nikita/go/src/github.com/polisgo2020/search-K1ta/main.go:26 +0x7b2
```

2020-04-14 09:22 UTC, K1ta commented on main.go
> +	exitIfNotEnoughArgs := func(length int) {
Поправил. Также перешел на [urfave/cli](https://github.com/urfave/cli)

По поводу ошибки - не удалось воспроизвести. Чуть изменил лог, теперь должна целиком выводиться линия индекса, на которой падает.

2020-04-14 19:32 UTC, tariel-x commented on main.go
> +	exitIfNotEnoughArgs := func(length int) {
Строил на этих данных: https://github.com/polisgo2020/main/tree/master/books
Так:
```
$ go run -race main.go server.go build ~/go/src/github.com/polisgo2020/main/books/ index.data
```
И тогда получается
```
$ go run -race main.go server.go start index.txt 8080
Cannot read index from file 'index.txt': invalid format of words map in index. Line: 9:02:[2]
exit status 1
```

2020-04-14 19:33 UTC, tariel-x commented on main.go
> +	exitIfNotEnoughArgs := func(length int) {
https://gist.github.com/tariel-x/53e3fefa894d972b530c8db6a87f1867

файл с индексом

2020-04-15 05:42 UTC, K1ta commented on main.go
> +	exitIfNotEnoughArgs := func(length int) {
Понял. Не учел того, что двоеточие в названии текста может быть)

2020-04-15 09:35 UTC, K1ta commented on main.go
> +	exitIfNotEnoughArgs := func(length int) {
Поправил. Также добавил тесты на этот случай

2020-04-15 18:35 UTC, tariel-x approved these changes

2020-04-16 06:20 UTC, merged